name: torch
channels:
  - pytorch
  - defaults
dependencies:
  - pytorch
  - torchvision
  - cuda91
  - h5py
  - matplotlib
  - imageio
  - scikit-image
  - pip
  - pip:
    - rospkg
    - catkin_pkg

